flares = {
	"алхимик": "flares/алхимик.jpg",
	"амеба": "flares/амёба.jpg",
	"антиматерия": "flares/антиматерия.jpg",
	"аристократ": "flares/аристократ.jpg",
	"аркада": "flares/аркада.jpg",
	"ас": "flares/ас.jpg",
	"бандит": "flares/бандит.jpg",
	"бастион": "flares/бастион.jpg",
	"безумец": "flares/безумец.jpg",
	"болезнь": "flares/болезнь.jpg",
	"брюзга": "flares/брюзга.jpg",
	"вакуум": "flares/вакуум.jpg",
	"варвар": "flares/варвар.jpg",
	"варпия": "flares/варпия.jpg",
	"вирус": "flares/вирус.jpg",
	"вихрь": "flares/вихрь.jpg",
	"вместилище": "flares/вместилище.jpg",
	"воитель": "flares/воитель.jpg",
	"вокалист": "flares/вокалист.jpg",
	"вольный": "flares/вольный.jpg",
	"ворюга": "flares/ворюга.jpg",
	"вымогатель": "flares/вымогатель.jpg",
	"вычислитель": "flares/вычислитель.jpg",
	"генерал": "flares/генерал.jpg",
	"гений": "flares/гений.jpg",
	"гипноз": "flares/гипноз.jpg",
	"горгона": "flares/горгона.jpg",
	"гравитон": "flares/гравитон.jpg",
	"грибок": "flares/грибок.jpg",
	"громила": "flares/громила.jpg",
	"грязь": "flares/грязь.jpg",
	"гуль": "flares/гуль.jpg",
	"двойка": "flares/двойка.jpg",
	"дворецкий": "flares/дворецкий.jpg",
	"демон": "flares/демон.jpg",
	"дервиш": "flares/дервиш.jpg",
	"диверсант": "flares/диверсант.jpg",
	"дикообраз": "flares/дикообраз.jpg",
	"диктатор": "flares/диктатор.jpg",
	"дипломат": "flares/дипломат.jpg",
	"доппельгенгер": "flares/доппельгенгер.jpg",
	"древний": "flares/древний.jpg",
	"жало": "flares/жало.jpg",
	"животное": "flares/животное.jpg",
	"жулик": "flares/жулик.jpg",
	"жучка": "flares/жучка.jpg",
	"задира": "flares/задира.jpg",
	"захватчик": "flares/захватчик.jpg",
	"зеркало": "flares/зеркало.jpg",
	"злюка": "flares/злюка.jpg",
	"зомби": "flares/зомби.jpg",
	"избранный": "flares/избранный.jpg",
	"изобличитель": "flares/изобличитель.jpg",
	"инженер": "flares/инженер.jpg",
	"интендант": "flares/интендант.jpg",
	"инь-ян": "flares/инь-ян.jpg",
	"искатель": "flares/искатель.jpg",
	"исследователь": "flares/исследователь.jpg",
	"кавалерист": "flares/кавалерист.jpg",
	"камикадзе": "flares/камикадзе.jpg",
	"карманник": "flares/карманник.jpg",
	"киборг": "flares/киборг.jpg",
	"клешня": "flares/клешня.jpg",
	"клон": "flares/клон.jpg",
	"клоп": "flares/клоп.jpg",
	"колотун": "flares/колотун.jpg",
	"коррдинатор": "flares/коррдинатор.jpg",
	"крио": "flares/крио.jpg",
	"кристалл": "flares/кристалл.jpg",
	"ксенофил": "flares/ксенофил.jpg",
	"куколка": "flares/куколка.jpg",
	"лазер": "flares/лазер.jpg",
	"левиафан": "flares/левиафан.jpg",
	"ленивец": "flares/ленивец.jpg",
	"лихач": "flares/лихач.jpg",
	"ловкач": "flares/ловкач.jpg",
	"любовь": "flares/любовь.jpg",
	"мазохист": "flares/мазохист.jpg",
	"макрон": "flares/макрон.jpg",
	"механизм": "flares/механизм.jpg",
	"мими": "flares/мими.jpg",
	"мимик": "flares/мимик.jpg",
	"мираж": "flares/мираж.jpg",
	"молния": "flares/молния.jpg",
	"мститель": "flares/мститель.jpg",
	"мудрец": "flares/мудрец.jpg",
	"мусорщик": "flares/мусорщик.jpg",
	"мутант": "flares/мутант.jpg",
	"наниматель": "flares/наниматель.jpg",
	"наемник": "flares/наёмник.jpg",
	"невеста": "flares/невеста.jpg",
	"нытик": "flares/нытик.jpg",
	"обжора": "flares/обжора.jpg",
	"оракул": "flares/оракул.jpg",
	"орда": "flares/орда.jpg",
	"падальщик": "flares/падальщик.jpg",
	"паразит": "flares/паразит.jpg",
	"партизан": "flares/партизан.jpg",
	"пасть": "flares/пасть.jpg",
	"патриот": "flares/патриот.jpg",
	"пацифист": "flares/пацифист.jpg",
	"пентаформа": "flares/пентаформа.jpg",
	"перевертыш": "flares/перевёртыш.jpg",
	"перерожденный": "flares/перерождённый.jpg",
	"пигмей": "flares/пигмей.jpg",
	"пират": "flares/пират.jpg",
	"победитель": "flares/победитель.jpg",
	"подстрекатель": "flares/подстрекатель.jpg",
	"подхалим": "flares/подхалим.jpg",
	"преобразователь": "flares/преобразователь.jpg",
	"прилив": "flares/прилив.jpg",
	"прилипала": "flares/прилипала.jpg",
	"провидец": "flares/провидец.jpg",
	"промышленник": "flares/промышленник.jpg",
	"пророк": "flares/пророк.jpg",
	"пульт": "flares/пульт.jpg",
	"пустота": "flares/пустота.jpg",
	"путешественник": "flares/путешественник.jpg",
	"пушечное_мясо": "flares/пушечное_мясо.jpg",
	"разбойник": "flares/разбойник.jpg",
	"разум": "flares/разум.jpg",
	"растение": "flares/растение.jpg",
	"реактор": "flares/реактор.jpg",
	"резерв": "flares/резерв.jpg",
	"садист": "flares/садист.jpg",
	"салага": "flares/салага.jpg",
	"саранча": "flares/саранча.jpg",
	"симбиот": "flares/симбиот.jpg",
	"сирена": "flares/сирена.jpg",
	"скептик": "flares/скептик.jpg",
	"скрытень": "flares/скрытень.jpg",
	"скряга": "flares/скряга.jpg",
	"слабак": "flares/слабак.jpg",
	"созерцатель": "flares/созерцатель.jpg",
	"сорвиголова": "flares/сорвиголова.jpg",
	"сосед": "flares/сосед.jpg",
	"судья": "flares/судья.jpg",
	"таракан": "flares/таракан.jpg",
	"тень": "flares/тень.jpg",
	"тик-так": "flares/тик-так.jpg",
	"тиран": "flares/тиран.jpg",
	"токсин": "flares/токсин.jpg",
	"торговец": "flares/торговец.jpg",
	"турист": "flares/турист.jpg",
	"удильщик": "flares/удильщик.jpg",
	"узурпатор": "flares/узурпатор.jpg",
	"утроитель": "flares/утроитель.jpg",
	"фантазм": "flares/фантазм.jpg",
	"филантроп": "flares/филантроп.jpg",
	"фокусник": "flares/фокусник.jpg",
	"фурия": "flares/фурия.jpg",
	"хакер": "flares/хакер.jpg",
	"хронос": "flares/хронос.jpg",
	"целитель": "flares/целитель.jpg",
	"цитадел": "flares/цитадел.jpg",
	"чародей": "flares/чародей.jpg",
	"человек": "flares/человек.jpg",
	"червоточина": "flares/червоточина.jpg",
	"червь": "flares/червь.jpg",
	"шизоид": "flares/шизоид.jpg",
	"шулер": "flares/шулер.jpg",
	"шут": "flares/шут.jpg",
	"эмпат": "flares/эмпат.jpg",
	"этик": "flares/этик.jpg",
	"ящер": "flares/ящер.jpg"
}

aliens = {
	"патриот":"aliens/patriot.jpg",
	"вакуум": "aliens/vacuum.jpg",
	"пушечное мясо": "aliens/pushechnoe_myaso.jpg",
	"алхимик": "aliens/alhimik.jpg",
	"амеба": "aliens/ameba.jpg",
	"амеба": "aliens/ameba.jpg",
	"антиматерия": "aliens/antimateriya.jpg",
	"архитектор": "aliens/arhitektor.jpg",
	"аристократ": "aliens/aristokrat.jpg",
	"аркада": "aliens/arkada.jpg",
	"ас": "aliens/as.jpg",
	"бандит": "aliens/bandit.jpg",
	"барахольщик": "aliens/baraholshik.jpg",
	"бастион": "aliens/bastion.jpg",
	"безумец": "aliens/bezumec.jpg",
	"болезнь": "aliens/bolezn.jpg",
	"брюзга": "aliens/bryuzga.jpg",
	"целитель": "aliens/celitel.jpg",
	"чародей": "aliens/charodey.jpg",
	"частица": "aliens/chastica.jpg",
	"человек": "aliens/chelovek.jpg",
	"черепаха": "aliens/cherepaha.jpg",
	"червь": "aliens/cherv.jpg",
	"червоточина": "aliens/chervotochina.jpg",
	"цитадел": "aliens/citadel.jpg",
	"клон": "aliens/clon.jpg",
	"дармоед": "aliens/darmoed.jpg",
	"демон": "aliens/demon.jpg",
	"дервиш": "aliens/dervish.jpg",
	"дикобраз": "aliens/dikobraz.jpg",
	"диктатор": "aliens/diktator.jpg",
	"дипломат": "aliens/diplomat.jpg",
	"диверсант": "aliens/diversant.jpg",
	"доппельгангер": "aliens/doppelganger.jpg",
	"древний": "aliens/drevniy.jpg",
	"дворецкий": "aliens/dvoreckiy.jpg",
	"двойка": "aliens/dvoyka.jpg",
	"эмпат": "aliens/empat.jpg",
	"этик": "aliens/etik.jpg",
	"фантазм": "aliens/fantazm.jpg",
	"филантроп": "aliens/filantrop.jpg",
	"фокусник": "aliens/fokusnik.jpg",
	"фурия": "aliens/furia.jpg",
	"генерал": "aliens/general.jpg",
	"гений": "aliens/geniy.jpg",
	"гипнос": "aliens/gipnos.jpg",
	"голод": "aliens/golod.jpg",
	"горгона": "aliens/gorgona.jpg",
	"гравитон": "aliens/graviton.jpg",
	"грибок": "aliens/gribok.jpg",
	"громила": "aliens/gromila.jpg",
	"грязь": "aliens/gryaz.jpg",
	"гуль": "aliens/gul.jpg",
	"хакер": "aliens/hacker.jpg",
	"хирург": "aliens/hirurg.jpg",
	"хронос": "aliens/hronos.jpg",
	"ии": "aliens/ii.jpg",
	"император": "aliens/imperator.jpg",
	"инь-ян": "aliens/in-yan.jpg",
	"инженер": "aliens/injener.jpg",
	"интендант": "aliens/intendant.jpg",
	"ипохондрик": "aliens/ipohondrik.jpg",
	"искатель": "aliens/iskatel.jpg",
	"исследователь": "aliens/issledovatel.jpg",
	"избранный": "aliens/izbranniy.jpg",
	"изобличитель": "aliens/izoblichitel.jpg",
	"жало": "aliens/jalo.jpg",
	"животное": "aliens/jivotnoe.jpg",
	"камикадзе": "aliens/kamikadze.jpg",
	"карманник": "aliens/karmannik.jpg",
	"кавалерист": "aliens/kavalerist.jpg",
	"киборг": "aliens/kiborg.jpg",
	"клешня": "aliens/kleshnya.jpg",
	"клоп": "aliens/klop.jpg",
	"колотун": "aliens/kolotun.jpg",
	"координатор": "aliens/koordinator.jpg",
	"крио": "aliens/krio.jpg",
	"кристалл": "aliens/kristal.jpg",
	"ксенофил": "aliens/ksenofil.jpg",
	"куколка": "aliens/kukolka.jpg",
	"культ": "aliens/kult.jpg",
	"лазер": "aliens/lazer.jpg",
	"ленивец": "aliens/lenivec.jpg",
	"левиафан": "aliens/leviafan.jpg",
	"лихач": "aliens/lihach.jpg",
	"ловкач": "aliens/lovkach.jpg",
	"любовь": "aliens/lubov.jpg",
	"макрон": "aliens/macron.jpg",
	"мазохист": "aliens/mazohist.jpg",
	"механизм": "aliens/mehanizm.jpg",
	"мими": "aliens/mimi.jpg",
	"мимик": "aliens/mimik.jpg",
	"мираж": "aliens/mirazh.jpg",
	"множественность": "aliens/mnozhestvennost.jpg",
	"молния": "aliens/molniya.jpg",
	"мститель": "aliens/mstitel.jpg",
	"мудрец": "aliens/mudrec.jpg",
	"мусорщик": "aliens/musorshik.jpg",
	"мутант": "aliens/mutant.jpg",
	"наемник": "aliens/naemnik.jpg",
	"наниматель": "aliens/nanimatel.jpg",
	"невеста": "aliens/nevesta.jpg",
	"нытик": "aliens/nitik.jpg",
	"обжора": "aliens/obzhora.jpg",
	"оракул": "aliens/orakul.jpg",
	"орда": "aliens/orda.jpg",
	"пацифист": "aliens/pacifist.jpg",
	"падальщик": "aliens/padalshik.jpg",
	"паразит": "aliens/parazit.jpg",
	"партизан": "aliens/partizan.jpg",
	"пасть": "aliens/past.jpg",
	"пентаформа": "aliens/pentaforma.jpg",
	"перерожденный": "aliens/pererozhdenniy.jpg",
	"перерожденный": "aliens/pererozhdenniy.jpg",
	"перевертыш": "aliens/perevertish.jpg",
	"перевертыш": "aliens/perevertish.jpg",
	"перфекционист": "aliens/perfekcionist.jpg",
	"пигмей": "aliens/pigmey.jpg",
	"пират": "aliens/pirat.jpg",
	"пламенный танцор": "aliens/plamenniy_tancor.jpg",
	"плащ": "aliens/plash.jpg",
	"победитель": "aliens/pobeditel.jpg",
	"подхалим": "aliens/podhalim.jpg",
	"подстрекатель": "aliens/podstrekatel.jpg",
	"преобразователь": "aliens/preobrazovatel.jpg",
	"претендент": "aliens/pretendent.jpg",
	"прилипала": "aliens/prilipala.jpg",
	"промышленник": "aliens/promishlennik.jpg",
	"пророк": "aliens/prorok.jpg",
	"провидец": "aliens/providec.jpg",
	"пульт": "aliens/pult.jpg",
	"пустота": "aliens/pustota.jpg",
	"путешественник": "aliens/puteshestvennik.jpg",
	"растение": "aliens/rastenie.jpg",
	"разбойник": "aliens/razboynik.jpg",
	"разум": "aliens/razum.jpg",
	"реактор": "aliens/reaktor.jpg",
	"реинкарнатор": "aliens/reinkarnator.jpg",
	"резерв": "aliens/rezerv.jpg",
	"садист": "aliens/sadist.jpg",
	"салага": "aliens/salaga.jpg",
	"саранча": "aliens/sarancha.jpg",
	"сердоболец": "aliens/serdobolec.jpg",
	"шулер": "aliens/shuler.jpg",
	"шут": "aliens/shut.jpg",
	"симбиот": "aliens/simbiot.jpg",
	"сирена": "aliens/sirena.jpg",
	"скептик": "aliens/skeptik.jpg",
	"скрытень": "aliens/skriten.jpg",
	"скряга": "aliens/skryaga.jpg",
	"слабак": "aliens/slabak.jpg",
	"сорвиголова": "aliens/sorvigolova.jpg",
	"сосед": "aliens/sosed.jpg",
	"созерцатель": "aliens/sozercatel.jpg",
	"судья": "aliens/sudya.jpg",
	"сжиматель": "aliens/szhimatel.jpg",
	"таракан": "aliens/tarakan.jpg",
	"тень": "aliens/ten.jpg",
	"тик-так": "aliens/tik-tak.jpg",
	"тиран": "aliens/tiran.jpg",
	"токсин": "aliens/toksin.jpg",
	"торгаш": "aliens/torgash.jpg",
	"торговец": "aliens/torgovec.jpg",
	"трус": "aliens/trus.jpg",
	"турист": "aliens/turist.jpg",
	"удильщик": "aliens/udilshik.jpg",
	"утроитель": "aliens/utroitel.jpg",
	"увалень": "aliens/uvalen.jpg",
	"узурпатор": "aliens/uzurpator.jpg",
	"варпия": "aliens/varpiya.jpg",
	"варвар": "aliens/varvar.jpg",
	"вычислитель": "aliens/vichislitel.jpg",
	"вихрь": "aliens/vihr.jpg",
	"вымогатель": "aliens/vimogatel.jpg",
	"вирус": "aliens/virus.jpg",
	"вместилище": "aliens/vmestilishe.jpg",
	"воитель": "aliens/voitel.jpg",
	"вокалист": "aliens/vokalist.jpg",
	"вольный": "aliens/volniy.jpg",
	"ворюга": "aliens/voryuga.jpg",
	"ящер": "aliens/yasher.jpg",
	"задира": "aliens/zadira.jpg",
	"захватчик": "aliens/zahvatchik.jpg",
	"зеркало": "aliens/zerkalo.jpg",
	"жучка": "aliens/zhuchka.jpg",
	"жулик": "aliens/zhulik.jpg",
	"злой близнец": "aliens/zloy_bliznec.jpg",
	"злюка": "aliens/zlyuka.jpg",
	"знаток": "aliens/znatokjpg.jpg",
	"зомби": "aliens/zombi.jpg",
	"олигарх":"essence_aliens/oligarh.jpg",
	"анархист":"essence_aliens/anarhist.jpg",
	"чужой":"essence_aliens/chuzhoy.jpg",
	"ассистент":"essence_aliens/assistent.jpg",
	"кошмар":"essence_aliens/koshmar.jpg",
	"няня":"essence_aliens/nyanya.jpg",
	"шериф":"essence_aliens/sherif.jpg",
	"шизоид":"essence_aliens/shizoid.jpg",
}

essence_aliens = {
	"олигарх": "essence_aliens/oligarh_karti.jpg",
	"анархист": "essence_aliens/anarhist_karti.jpg",
	"ассистент": "essence_aliens/assistent_carti.jpg",
	"чужой": "essence_aliens/chuzhoy_karti.jpg",
	"кошмар": "essence_aliens/koshmar_karti.jpg",
	"няня": "essence_aliens/nyanya_karti.jpg",
	"шериф": "essence_aliens/sherif_karti.jpg",
	"шизоид": "essence_aliens/shizoid_karti.jpg",
	"захватчик":"essence_aliens/zahvatchik_karti.jpg"
}

stations = {
	"аванпост пришельцев": "other_cards/с_аванпост_пришельцев.jpg",
	"большой космический лазер": "other_cards/с_большой_космический_лазер.jpg",
	"генератор космической энергии": "other_cards/с_генератор_космической_энергии.jpg",
	"генератор щита": "other_cards/с_генератор_щита.jpg",
	"казармы штурмового дисанта": "other_cards/с_казармы_штурмового_дисанта.jpg",
	"маскировочный купол": "other_cards/с_маскировочный_купол.jpg",
	"межпространственный ретранслятор": "other_cards/с_межпространственный_ретранслятор.jpg",
	"наблюдательная платформа": "other_cards/с_наблюдательная_платформа.jpg",
	"тактический спутник": "other_cards/с_тактический_спутник.jpg",
	"темпоральная матрица": "other_cards/с_темпоральная_матрица.jpg"
}

technologies = {
	"аппарат энигма.jpg": "other_cards/аппарат_энигма.jpg",
	"бомба сотворения.jpg": "other_cards/бомба_сотворения.jpg",
	"вакуумные турбины.jpg": "other_cards/вакуумные_турбины.jpg",
	"варп ключ.jpg": "other_cards/варп_ключ.jpg",
	"генератор космического поля.jpg": "other_cards/генератор_космического_поля.jpg",
	"глюонные мины.jpg": "other_cards/глюонные_мины.jpg",
	"двигатель бесконечности.jpg": "other_cards/двигатель_бесконечности.jpg",
	"дельта-сканнеры.jpg": "other_cards/дельта-сканнеры.jpg",
	"квакс.jpg": "other_cards/квакс.jpg",
	"кварковые батареи.jpg": "other_cards/кварковые_батареи.jpg",
	"коллапсиевый корпус.jpg": "other_cards/коллапсиевый_корпус.jpg",
	"корабль поколений.jpg": "other_cards/корабль_поколений.jpg",
	"ксеоновые лазеры.jpg": "other_cards/ксеоновые_лазеры.jpg",
	"лунная пушка.jpg": "other_cards/лунная_пушка.jpg",
	"омега-ракета.jpg": "other_cards/омега-ракета.jpg",
	"плазменные двигатели.jpg": "other_cards/плазменные_двигатели.jpg",
	"поставщик помех.jpg": "other_cards/поставщик_помех.jpg",
	"прометей.jpg": "other_cards/прометей.jpg",
	"семя предтеч.jpg": "other_cards/семя_предтеч.jpg",
	"энергеическая маскировка.jpg": "other_cards/энергеическая_маскировка.jpg"
}

hazards = {

}
